// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC59aP3HXo2TRt9YvtBNU7VqnjgnFaGjFk',
    appId: '1:786247972605:web:6b28136cee8cbd4f857094',
    messagingSenderId: '786247972605',
    projectId: 'lmsapp-5ab03',
    authDomain: 'lmsapp-5ab03.firebaseapp.com',
    storageBucket: 'lmsapp-5ab03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArgcDzZS5_w-vF6U_ljaQAuFT5G1-tScE',
    appId: '1:786247972605:android:302dc1be98701bbf857094',
    messagingSenderId: '786247972605',
    projectId: 'lmsapp-5ab03',
    storageBucket: 'lmsapp-5ab03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnnl8PYEIimOuZwMaarX8G1X31QpTU7U',
    appId: '1:786247972605:ios:cad96ff6dcf5c8b1857094',
    messagingSenderId: '786247972605',
    projectId: 'lmsapp-5ab03',
    storageBucket: 'lmsapp-5ab03.appspot.com',
    iosBundleId: 'com.example.livelocation',
  );
}
